CREATE TABLE Empresa (
  empresa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255),
  razao_social VARCHAR(255),
  cnpj VARCHAR(20) UNIQUE,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Permissoes (
  permissao_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255)
);

CREATE TABLE Recrutadores (
  recrutador_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  senha VARCHAR(255),
  empresa_id INTEGER,
  permissao_id INTEGER,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Cargos (
  cargo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255)
);

CREATE TABLE Senioridades (
  senioridade_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255)
);

CREATE TABLE Modalidades (
  modalidade_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255)
);

CREATE TABLE Vagas (
  vaga_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recrutador_id INTEGER,
  empresa_id INTEGER,
  titulo VARCHAR(255),
  descricao TEXT,
  cargo_id INTEGER,
  senioridade_id INTEGER,
  modalidade_id INTEGER,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Candidatos (
  candidato_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  senha VARCHAR(255),
  telefone VARCHAR(20),
  cpf VARCHAR(14) UNIQUE,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Curriculo (
  curriculo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidato_id INTEGER,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Candidatura (
  candidatura_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curriculo_id INTEGER,
  vaga_id INTEGER,
  status VARCHAR(50),
  pretencao_salarial NUMERIC(12, 2),
  data_candidatura TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Skills (
  skill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_skill VARCHAR(255),
  nome_skill VARCHAR(255)
);

CREATE TABLE Skills_Curriculo (
  skill_curriculo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_id INTEGER,
  curriculo_id INTEGER
);

CREATE TABLE Skills_Vaga (
  skill_vaga_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_id INTEGER,
  vaga_id INTEGER,
  nivel_skill VARCHAR(50),
  obrigatorio BOOLEAN DEFAULT FALSE,
  peso NUMERIC(5, 2)
);

CREATE TABLE ExperienciaCandidato (
  experiencia_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curriculo_id INTEGER,
  cargo_id INTEGER,
  salario NUMERIC(12, 2),
  senioridade_id INTEGER,
  descricao TEXT,
  empresa VARCHAR(255),
  data_inicio TIMESTAMP,
  data_fim TIMESTAMP,
  is_atual BOOLEAN DEFAULT FALSE
);

CREATE TABLE Escolaridade (
  escolaridade_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  curriculo_id INTEGER,
  nome_instituicao VARCHAR(255),
  curso VARCHAR(255),
  tipo_escolaridade VARCHAR(100),
  concluido BOOLEAN DEFAULT FALSE,
  modalidade VARCHAR(100),
  data_inicio TIMESTAMP,
  data_fim TIMESTAMP
);

CREATE TABLE Badges (
  badge_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255)
);

CREATE TABLE Badges_Candidato (
  badge_candidato_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  badge_id INTEGER,
  candidato_id INTEGER
);

CREATE TABLE MetasESG (
  meta_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id INTEGER,
  badge_id INTEGER,
  porcentagem NUMERIC(5, 2),
  quantidade NUMERIC(10, 2)
);

CREATE TABLE Contratacao (
  contratacao_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidatura_id INTEGER,
  salario NUMERIC(12, 2)
);

CREATE TABLE AderenciaMetasESG (
  aderencia_meta_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meta_id INTEGER,
  contratacao_id INTEGER
);

ALTER TABLE Recrutadores ADD CONSTRAINT fk_recrutadores_empresa FOREIGN KEY (empresa_id) REFERENCES Empresa (empresa_id) ON DELETE CASCADE;
ALTER TABLE Recrutadores ADD CONSTRAINT fk_recrutadores_permissao FOREIGN KEY (permissao_id) REFERENCES Permissoes (permissao_id) ON DELETE CASCADE;
ALTER TABLE Vagas ADD CONSTRAINT fk_vagas_recrutador FOREIGN KEY (recrutador_id) REFERENCES Recrutadores (recrutador_id) ON DELETE CASCADE;
ALTER TABLE Vagas ADD CONSTRAINT fk_vagas_empresa FOREIGN KEY (empresa_id) REFERENCES Empresa (empresa_id) ON DELETE CASCADE;
ALTER TABLE Vagas ADD CONSTRAINT fk_vagas_cargo FOREIGN KEY (cargo_id) REFERENCES Cargos (cargo_id) ON DELETE CASCADE;
ALTER TABLE Vagas ADD CONSTRAINT fk_vagas_senioridade FOREIGN KEY (senioridade_id) REFERENCES Senioridades (senioridade_id) ON DELETE CASCADE;
ALTER TABLE Vagas ADD CONSTRAINT fk_vagas_modalidade FOREIGN KEY (modalidade_id) REFERENCES Modalidades (modalidade_id) ON DELETE CASCADE;
ALTER TABLE Curriculo ADD CONSTRAINT fk_curriculo_candidato FOREIGN KEY (candidato_id) REFERENCES Candidatos (candidato_id) ON DELETE CASCADE;
ALTER TABLE ExperienciaCandidato ADD CONSTRAINT fk_experiencia_curriculo FOREIGN KEY (curriculo_id) REFERENCES Curriculo (curriculo_id) ON DELETE CASCADE;
ALTER TABLE ExperienciaCandidato ADD CONSTRAINT fk_experiencia_cargo FOREIGN KEY (cargo_id) REFERENCES Cargos (cargo_id) ON DELETE CASCADE;
ALTER TABLE ExperienciaCandidato ADD CONSTRAINT fk_experiencia_senioridade FOREIGN KEY (senioridade_id) REFERENCES Senioridades (senioridade_id) ON DELETE CASCADE;
ALTER TABLE Escolaridade ADD CONSTRAINT fk_escolaridade_curriculo FOREIGN KEY (curriculo_id) REFERENCES Curriculo (curriculo_id) ON DELETE CASCADE;
ALTER TABLE Candidatura ADD CONSTRAINT fk_candidatura_curriculo FOREIGN KEY (curriculo_id) REFERENCES Curriculo (curriculo_id) ON DELETE CASCADE;
ALTER TABLE Candidatura ADD CONSTRAINT fk_candidatura_vaga FOREIGN KEY (vaga_id) REFERENCES Vagas (vaga_id) ON DELETE CASCADE;
ALTER TABLE Skills_Curriculo ADD CONSTRAINT fk_skills_curriculo_curriculo FOREIGN KEY (curriculo_id) REFERENCES Curriculo (curriculo_id) ON DELETE CASCADE;
ALTER TABLE Skills_Curriculo ADD CONSTRAINT fk_skills_curriculo_skill FOREIGN KEY (skill_id) REFERENCES Skills (skill_id) ON DELETE CASCADE;
ALTER TABLE Skills_Vaga ADD CONSTRAINT fk_skills_vaga_vaga FOREIGN KEY (vaga_id) REFERENCES Vagas (vaga_id) ON DELETE CASCADE;
ALTER TABLE Skills_Vaga ADD CONSTRAINT fk_skills_vaga_skill FOREIGN KEY (skill_id) REFERENCES Skills (skill_id) ON DELETE CASCADE;
ALTER TABLE Badges_Candidato ADD CONSTRAINT fk_badges_candidato_badge FOREIGN KEY (badge_id) REFERENCES Badges (badge_id) ON DELETE CASCADE;
ALTER TABLE Badges_Candidato ADD CONSTRAINT fk_badges_candidato_candidato FOREIGN KEY (candidato_id) REFERENCES Candidatos (candidato_id) ON DELETE CASCADE;
ALTER TABLE MetasESG ADD CONSTRAINT fk_metas_esg_empresa FOREIGN KEY (empresa_id) REFERENCES Empresa (empresa_id) ON DELETE CASCADE;
ALTER TABLE MetasESG ADD CONSTRAINT fk_metas_esg_badge FOREIGN KEY (badge_id) REFERENCES Badges (badge_id) ON DELETE CASCADE;
ALTER TABLE Contratacao ADD CONSTRAINT fk_contratacao_candidatura FOREIGN KEY (candidatura_id) REFERENCES Candidatura (candidatura_id) ON DELETE CASCADE;
ALTER TABLE AderenciaMetasESG ADD CONSTRAINT fk_aderencia_contratacao FOREIGN KEY (contratacao_id) REFERENCES Contratacao (contratacao_id) ON DELETE CASCADE;
ALTER TABLE AderenciaMetasESG ADD CONSTRAINT fk_aderencia_meta FOREIGN KEY (meta_id) REFERENCES MetasESG (meta_id) ON DELETE CASCADE;
